"""Add sentiment field to Tweet

Revision ID: 31b27e2b23df
Revises: 71df427fe3ff
Create Date: 2025-05-22 15:19:32.498107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31b27e2b23df'
down_revision = '71df427fe3ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=280),
               existing_nullable=False)

    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=280),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
