"""Remove image_category from Tweet

Revision ID: 46e8c1f17aea
Revises: d0ae1861b5ce
Create Date: 2025-05-22 18:32:56.888929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e8c1f17aea'
down_revision = 'd0ae1861b5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.drop_column('image_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tweet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_category', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
